name: 'Validate Pull Request'

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.py'
      - '**.tf'

jobs:
  format:
    name: 'Check Format'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
      
      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Python Format
        uses: psf/black@stable
        with:
          options: "--check --verbose"

  validate:
    name: 'Validate Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        working-directory: examples/simple
        run: terraform init

      - name: Terraform Validate
        working-directory: examples/simple
        run: terraform validate